FROM python:3.7.2-stretch as TestBench
ENV http_proxy ${http_proxy}
ENV https_proxy ${https_proxy}

COPY ./requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

FROM TestBench
COPY ./ /opt/app/
WORKDIR /opt/app/

RUN PYTHONPATH=pingfedsdk:src:$PYTHONPATH pytest --cov=src -vv --cov-report term-missing