version: 0.2

env:
  variables:
    VAR_Owner: Versent
    VAR_AppName: pypingfedsdk
    VAR_OAuthSecret: arn:aws:secretsmanager:ap-southeast-2:264748061542:secret:github/versent-builder-foTpJN
    VAR_DomainOwner: 264748061542
    VAR_Domain: internal-tools-versent

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Install all the test packages
      - apt update
      - apt install -y wget zip jq
      - pip install --upgrade pip
      - pip install --upgrade setuptools
      - pip install --upgrade wheel
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - pip install pipenv
      - pipenv lock --clear
      - pipenv lock -r --dev > requirements_test.txt
      - pip install -r requirements_test.txt
    finally:
      - printenv

  pre_build:  
    commands:
      - PYTHONPATH=PyPingFedSDK:src:$PYTHONPATH pytest --cov=PyPingFedSDK -vv --cov-report term-missing
      - flake8 --ignore=E501,E402 ./PyPingFedSDK
      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
  
  build:
    commands:
      - python PyPingFedSDK/docker_generate.py
  
  post-build:
    commands:
      - aws codeartifact login --tool twine --repository $VAR_AppName --domain $VAR_Domain --domain-owner $VAR_DomainOwner
      - python setup.py sdist bdist_wheel
    finally:
      - python -m twine upload --repository codeartifact dist/*

